system {
    host-name R2;
}

interfaces {
    ge-0/0/0 {
        description "Link to Cisco Router";
        unit 0 {
            family inet {
                address 10.0.0.2/30;
            }
        }
    }
}

routing-options {
    static {
        route 0.0.0.0/0 next-hop 10.0.0.1;
    }
}
